### PR TITLE
LPS-54875

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @scottland104 

Not really sure if you still review code.
You seem to be the Dev Lead for the Mail component?

Let me know if you want me to send this to somebody else

**Comment by scottland104** [comment]
You can skip me, and just directly send it to whoever is next in the chain.  Thanks.

**Comment by hhuijser** [comment]
Hey @scottland104 

You are the only one listed as Developer for Mail...
Who should I be forwarding this to?

**Comment by scottland104** [comment]
I not familiar with the process for merging code in core, and there are
very few changes to the mail portlet that come my way.  I think previous
PRs have gone straight to bchan.

**Pull request closed without merging**
